<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(EntityFrameworkVersion)" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(DependencyInjectionVersion)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\myNOC.EntityFramework.Query\myNOC.EntityFramework.Query.csproj" />
	</ItemGroup>

</Project>
