<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
		<Title>myNOC.EntityFramework.Query</Title>
		<Authors>myNOC LLC</Authors>
		<Description>Implements a Query Pattern to be used with EntityFramework</Description>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<Copyright>Copyright © myNOC LLC 2025</Copyright>
		<RepositoryUrl>https://github.com/erenken/queryPattern</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageProjectUrl>https://github.com/erenken/queryPattern</PackageProjectUrl>
		<EnablePackageValidation>true</EnablePackageValidation>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
		<None Include="LICENSE.txt" Pack="true" PackagePath="" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EntityFrameworkVersion)" />
	</ItemGroup>

</Project>
