<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkVersion)" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.5.1" />
		<PackageReference Include="MSTest.TestFramework" Version="4.5.1" />
		<PackageReference Include="coverlet.collector" Version="10.1.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NSubstitute" Version="6.2.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\myNOC.EntityFramework.Query\myNOC.EntityFramework.Query.csproj" />
		<ProjectReference Include="..\..\sample\QuerySample\QuerySample.csproj" />
	</ItemGroup>

</Project>
